kisslinux/kiss

kiss
In case of a package already exist in `$bin_dir` if it isn't built in that system (e.g. by copying the tar file manually from another `kiss` instance to `$bin_dir`), don't blindly install it but check if the depends are properly installed. Otherwise the binaries won't run properly.
=> install: add dependency check

README.md, kiss
Running `pkg_remove` prior to `pkg_install` had the benefit of removing any files in the system that **aren't** in the new version of the package (but exist in the currently installed version). It also has the benefit of **not** overwriting files owned by a different package (it instead skips them).
This PR creates copies of `rm`, `rmdir` and `tar` (and removes them afterwards) ensuring the commands will always be available.
This seems like the "least bad" solution to the problem as it prevents stray files between package upgrades. (We can later add a check for conflicting files between multiple packages and abort)
I think we should also consider setting `set -e` globally in the script.
=> kiss: Fix pkg_install if coreutils is reinstalled.

kiss
Rewriting manifest can be very massive, since `find` will just get whatever comes in first. [Gettext](https://github.com/kissx/packages/commit/b6531bb24a36174f7ec497135ed1bce503f63c17#diff-51174322c1306c4912143c1337533b10) has a long diff in `manifest` alone. After this commit, I hope we have one last massive manifest diff changes for each package, and the manifest changes will be reserved for the new/deleted file.
=> pkg_manifest: sort before writing to manifest file

kiss
Before a package installation this compares the tarball's manifest to all installed package's manifests and aborts if there is a conflict. This allows us to "dynamically" detect conflicts and remove the need for a `conflicts` file.
To workaround the issue of false positives with directories, directories are stripped from the tarball's manifest. This basically means that only matching **files** are checked for conflicts which is fine.
Closes #11
=> kiss: Added package conflicts.

kiss
- Adds a check in `pkg_conflicts` for conflicting **non** package files in the file-system.
- Packages are extracted to `$tar_dir`.
- Directories are created one by one.
- Files and file symlinks are moved one by one.
TODO: 
- Allows us to abort install on broken tarball.
=> kiss: Fix package installation bugs.

kiss
I actually forgot that the sticky bit only applies to the "mother" cache directory and doesn't work recursively (with the "main dirs") where the files are created (`$cac_dir/sources` and `$cac_dir/bin`).
**Why `chmod`? Why not `mkdir -m`?**
This is to ensure that when user upgrades (`kiss u`), the change should be applied instead of releasing yet another chroot.
=> cache: set sticky bit too to the children dirs

kiss
This adds a new function which checks each of the package's binaries and libraries using `ldd` for any runtime dependencies which may be missing from the `depends` file. This solves the issue of a package's build suite pulling in dependencies which aren't mentioned in the `depends` file (*which could lead to potential breakage through package removal*). 
A `diff` is displayed which shows what dependencies were added to the `depends` file. No deletions are done, only additions. 
Concerns about this creating circular dependencies are moot as the dependency solver checks dependencies using the files from the repositories and not the installed database. Even if the package manager falls back to using the installed database, it's highly highly unlikely that any of the circular-dependency prone …
=> kiss: Added function to dynamically set depends

kiss
=> kiss: remove fakeroot usage

kiss
This allows us to drop the `file` utility from `core`.
=> stripping: swap to readelf

kiss
Properly handle dependencies of packages passed on the command-line.
Testing:
- Duplicates not correctly filtered.
- Duplicates not correctly filtered.
=> Smarter dep handling

kiss
Source format:
```
git+https://github.com/dylanaraps/eiwd
git+https://github.com/dylanaraps/eiwd#4a2d30bd1b053a9f1e4373d17c2ae6f3ccbc4148
```
- Checksums are skipped over for git sources.
- Checksums work as normal for non-git sources in the same package.
- No caching support (for obvious reasons)
Issues:
- The checksums file will be empty if no non-git sources exist.
- You still have to run `kiss c pkg` even if no non-git sources.
=> Git support

kiss
Removed comment about using the literal escape character. Changed the comments describing the arguments to include the added non-literal escape character, and modified them slightly to keep everything from going above 80 columns (which seems to be the desired limit).
=> log: replace use of literal escape code error with printf %b

kiss
Info in comments.
TODO:
ISSUES:
Closes #37
=>  kiss: alternatives system

kiss
- Packages built with this PR's code will contain an additional `etcsums` file (installed to `/var/db/kiss/installed/pkg`). This contains the **original** checksums of the `/etc` files for that package version.
- On install of a package, a three-way check happens between the system's etc/file, the new etc/file and the etcsums etc/file. Depending on *how* they compare, kiss will either overwrite the existing etc/file or instead save the new file to etc/file.new.
- For existing packages (without `etcsums`), the package manager will **always** save a etc/file.new instead of overwriting the user's files (If merge with 2 points of data isn't possible).
TODO
=> kiss: 3-way etc checksums thing

README.md, kiss, kiss.1
- The package manager will now optionally show a  `diff` of all changes in the current `kiss update`. 
- The user's set `$PAGER` will be called with a fallback to `less`.
- This is opt-in via the `KISS_AUDIT` environment variable (*set it to 1*).
=> kiss: Add option to show diffs on update

kiss
adds a hook to be run when a build fails to `kiss`
=> add build-fail hook

kiss
busybox `diff` only supports unified diffs (therefore, the `-u` option is not available). However, GNU `diff` supports more diff formats and is not unified by default. Fortunately, both supports the `-U [num]` option which is POSIX compliant. We set it to `3` as a unified diff has three lines of context by default.
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/diff.html
=> kiss: pkg_fixdeps(): Make diff work across diff-erent implementations

kiss
Full rsync removal is possible so long as we replace it with a carefully written alternative using basic utilities. I implore you to test this PR and report and issues that arise. This touches one of the most important parts of the package manager and I'd like to ensure everything is correct before I push the green button.
Notes:
- The `awk` command simply reverses the manifest file. If you know of a more portable or smaller alternative, that'd be nice.
- The `stat` command prints the octal permissions though I may go ahead and replace this with `ls -l` and with code added to convert `-rwxrwxrwx` to the octal format. This same replacement would be used to remove the other `stat` call for ownership. (Parsing `ls -l` for permissions and/or ownership is considered safe for use in scripting). …
=> kiss: Drop rsync

kiss
this makes kiss' sed usage POSIX-compatible.
=> kiss: replace sed -i with redirection to a temp file

kiss
POSIX doesn't specify %*s for the printf command, with the rationale
that one can just put the variable there in place, do that.
=> kiss: remove non-POSIX printf * field width specifier

kiss
This would prevent an empty post-install log file from being created if there is no post-install script or if it's not executable.
=> kiss: Don't create empty post-install log file

kiss
Liberation fonts (i.e. Liberation Mono), which are available via `liberation-fonts` in the KISS main repository, do not support the "✓" glyph. No alternative or patched font sets are currently available in the main repo, so i think it makes sense to remove unsupported glyphs.
**source**: https://fonts2u.com/liberation-mono.font
=> kiss: remove unsupported glyph ("✓")

kiss
Simple pr that adds support for submodules basically adds no time to repos that dont have submodules as far as I can tell.
=> Add submodule support to kiss.

contrib/kiss-depends, contrib/kiss-export, contrib/kiss-maintainer, contrib/kiss-manifest, contrib/kiss-revdepends, contrib/kiss-size
Using the current directory as the name of the package to be operated on, like how `kiss` does it. Besides this I made a small change to `kiss-maintainers`, it now allows multiple parameters, for example `kiss-maintainers git mpv`
=> Add CRUX style usage to contrib scripts

kiss
sls syntax now compatible with doas/sudo
Depends on https://github.com/kisslinux/community/pull/1192
=> kiss: update sls syntax

contrib/kiss-depends, contrib/kiss-export, contrib/kiss-fork, contrib/kiss-link, contrib/kiss-maintainer, contrib/kiss-manifest, contrib/kiss-outdated, contrib/kiss-reset, contrib/kiss-revdepends, contrib/kiss-size
Some minor nitpicks for contrib scripts.
The biggest functional change is `sort -u` to `uniq -u`, which preserves ordering.
=> Contrib cleanup

kiss
If the user has modified the file in /etc/, it will not be removed
and a message will be printed to the screen. If the file is
unmodified, it will be removed like any other.
This uses the etcsums file for comparison of checksums. The file
is also used during installation handling of files in /etc/.
Closes #181
=> kiss: Add handling of /etc/ files to removal action.

contrib/kiss-export
Follow kiss package manager new naming scheme in kiss-export also.
=> kiss-export: new naming scheme for tarballs

contrib/kiss-preferred, kiss
Wrote a small script to get the "in-use" file for every "alternative".
The goal is to be able to maintain the same software stack on multiple machines. Plan to take the output of this command on one machine and pipe into `kiss a` on another (assuming the same set of programs are installed).
When writing the extension, I noticed `kiss own '/usr/bin/['` didn't work, so this PR also includes the one line fix for that too.
Example output
```
./contrib/kiss-preferred | head -n4
busybox /usr/bin/[
busybox /usr/bin/base64
busybox /usr/bin/basename
busybox /usr/bin/blkdiscard
```
=> kiss-preferred: new utility to list all current conflicts resolutions. 

kiss
sbase utilities don't accept flags after arguments begin, meaning that
the '--' is accepted as an argument instead of the "end flag", which
causes the utility to fail because it looks for a file named '--'.
=> pkg_remove(): Fix reverse dependency resolving on sbase grep

contrib/kiss-size
Previously, if kiss-size was ran on a package that owns a lot of
files, kiss-size would error out. This is because du wasn't
able to handle the number of files provided to it.
This patch solves this issue, by avoiding the generation of the 'files'
variable, and instead piping directly into xargs which then feeds the
files to du.
For an example package that breaks with the previous implementation,
see https://github.com/ehawkvu/kiss-tex/tree/master/texlive/texlive-fontsextra
which installs around 94,000 files.
=> kiss-size: fix bug when kiss-size runs on big packages
